### ISSUE TITLE
Api key expired

### ISSUE THREAD

**Issue by aganglada** [googlemaps/transport-tracker#1]
I'm getting this error, so the map is not showing up

`Google Maps API error: ExpiredKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#expired-key-map-error`

**Comment by domesticmouse** [comment]
I'm guessing you created yourself a valid Google Maps key following the process outlined at [Get API Key](https://developers.google.com/maps/documentation/javascript/get-api-key)? In which case, wait five minutes and try again. Making distributed systems consistent is hard. Sorry!

**Comment by aganglada** [comment]
Ahh! Sorry i meant in your demo https://io-bus-tracker.appspot.com/ :)

**Comment by domesticmouse** [comment]
Ahh yes, I'll fix that. Thanks!

**Comment by aganglada** [comment]
you're welcome 👍
