### ISSUE TITLE
instructions not upto date

### ISSUE THREAD

**Issue by kmukul123** [googlemaps/transport-tracker#17]
Hi,
 are the instructions on 
https://codelabs.developers.google.com/codelabs/transport-tracker-backend/#3 upto date? When i run npm run main I see an answer as zero.
Thanks

**Comment by domesticmouse** [comment]
The github repository that represents the codelab is https://github.com/googlecodelabs/transport-tracker-codelab/

It looks like your issue might already have been raised on https://github.com/googlecodelabs/transport-tracker-codelab/issues but please, confirm if that is the case, and if not raise a new issue.

I'm closing this issue as you aren't asking about the code in this repository. Please feel free to cross link this issue on that repository's issue tracker. Thanks!
