### ISSUE TITLE
andriod project doesnt compile

### ISSUE THREAD

**Issue by kmukul123** [googlemaps/transport-tracker#18]
Error:Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  D:\src\transport-tracker\android\app\src\debug\google-services.json
  D:\src\transport-tracker\android\app\google-services.json

**Comment by stephenmcd** [comment]
In the README, you'll find the documentation required to get started:

https://developers.google.com/maps/solutions/transport-tracker/start

The setup steps there for Android mention configuring access to the Firebase database. Looking at the error, it would appear you've not done that.
