### ISSUE TITLE
map - 127.0.0.1:8080 - page shows header and no content

### ISSUE THREAD

**Issue by gitcostan** [googlemaps/transport-tracker#19]
hello,

i have successfully setup the "backend", "android app" and these are running on my local desktop nodejs server and successfully updating the firebase database.

i followed all instructions for "map" module and "npm install" and "npm run main" executed without errors. Then it shows me "server started at http://127.0.0.1:8080" but when i open this url in chrome browser it shows the header and 3 grey circles at the bottom, but no content is shown....when i check the javascript console didn't show any error.

please advise what could be my mistake.

thanks.

**Comment by domesticmouse** [comment]
I'd suggest working through these two codelabs [transport-tracker-backend](https://codelabs.developers.google.com/codelabs/transport-tracker-backend/#0) and [transport-tracker-map](https://codelabs.developers.google.com/codelabs/transport-tracker-map/#0). That will hopefully give you a better vantage point to understand this code base. Thanks!
