### ISSUE TITLE
User authentication fails in some Android devices even when correct credentials are entered

### ISSUE THREAD

**Issue by gitcostan** [googlemaps/transport-tracker#23]
Hello

On some Android devices the app opens. When correct email password is entered, it still shows "user authentication failed" error. But I'm able to successfully test it using emulator on equivalent Android versions. Please advise how to resolve this.

Thanks

**Comment by stephenmcd** [comment]
I'd suggest looking at the following which covers debugging auth failures:

https://stackoverflow.com/questions/38038034/firebase-on-android-how-to-check-firebase-auth-failed-reason
