### ISSUE TITLE
Map is not coming in my setup

### ISSUE THREAD

**Issue by ankitjaiinn** [googlemaps/transport-tracker#25]
Hi Their,

I have setup the backend and map application on my server. Both applications are running fine. But when i am seeing the map application, i am only seeing the html part. Nothing is happening their. Below is the URL where i setup my application. Can you please help me identifying the error which i am making.
http://35.162.108.80:8080/

**Comment by domesticmouse** [comment]
What do you see in the web browser console? I'm guessing your Maps API key is not correct.

**Comment by ankitjaiinn** [comment]
I am able to solve the issue myself. It is not mentioned anywhere in the documentation that we have to allow read permission in firebase real time database. It is working after that.
