### ISSUE TITLE
Cannot show tracked vehicle on map

### ISSUE THREAD

**Issue by ThenTen** [googlemaps/transport-tracker#26]
The admin only showing the simulated tracking vehicle, i already disable the simulation at tracker_configuration.json for backend. The vehicle movement points are successfully stored at firebase thought.

What are the additional steps required to show my tracked vehicle on the map?

**Comment by domesticmouse** [comment]
Please review the following codelabs:
 - [Transport Tracker Backend](https://codelabs.developers.google.com/codelabs/transport-tracker-backend/index.html?index=..%2F..%2Findex#0)
 - [Transport Tracker Map](https://codelabs.developers.google.com/codelabs/transport-tracker-map/index.html?index=..%2F..%2Findex#0)

**Comment by quarky912** [comment]
@ThenTen are you able to get real tracking of vehicles?

**Comment by ThenTen** [comment]
@quarky912 nope, it seem like this feature requires to purchase google map premium plan.
