### ISSUE TITLE
Unable to run Backend

### ISSUE THREAD

**Issue by akhiljain05** [googlemaps/transport-tracker#28]
Backend code on test  give me below error 
![image](https://user-images.githubusercontent.com/33246028/33129503-157361ce-cfb6-11e7-8bbe-ce136c3755c1.png)

Please help .

**Comment by domesticmouse** [comment]
I'm curious which version of Node.js you are running? Have you tried running Node inside of either Window's Linux sub system, or inside Docker?

**Comment by akhiljain05** [comment]
my node version:- 5.5.1
I am tried this in windows 8

**Comment by domesticmouse** [comment]
I don't have access to any Windows 8 machines, so I can't debug what is going wrong here. I'd suggest you use a linux server in the cloud, e.g. [Google Cloud Compute Engine](https://cloud.google.com/compute/).
