### ISSUE TITLE
Tracking of 4 busses owned by a private firm over the map 

### ISSUE THREAD

**Issue by quarky912** [googlemaps/transport-tracker#33]
Sir I need to ask you that if this code can be used to track 4 to 5 busses owned by an institution? and what are the changes required to get this functionality in the original code. how can I edit the gtfs TEXT files to get this functionality. I am learning this code for last one month. Please help. @domesticmouse @stephenmcd

**Comment by quarky912** [comment]
If I do not want to use bus simulator then what do I need to do? I am not able to get this if I want to track a real device, then what should be added and what should not be added?

**Comment by domesticmouse** [comment]
Please go through the codelabs for this code:
 - [Transport Tracker Backend](https://codelabs.developers.google.com/codelabs/transport-tracker-backend/index.html)
 - [Transport Tracker Map](https://codelabs.developers.google.com/codelabs/transport-tracker-map/index.html)

**Comment by quarky912** [comment]
Sir, I'm grateful to you for your kind response. I would like to tell you
that I've already gone through the link you provided.
I'm not able to understand what do I need to do for displaying real time
location of 4 buses on a map and not using the bus_simulator.js

I request you to please help me through this

**Comment by saifisohail** [comment]
Hey @quarky912 are you able to show locations of buses on map I'm also facing the same problem. I'm getting those locations in raw data but it's not showing in web app please tell me if you got this I've been working on it from weeks but I'm not getting how to show those locations on map
