### ISSUE TITLE
Missing script in transport-tracker/admin/package.json

### ISSUE THREAD

**Issue by leonharbour** [googlemaps/transport-tracker#34]
```
transport-tracker/admin/>npm run main
npm ERR! missing script: main
```

transport-tracker/admin/package.json
"main": "index.js"

```
{
  "name": "admin",
  "version": "1.0.0",
  "description": "Transport Tracker admin",
  "main": "index.js",
  "author": "Stephen McDonald <stephenmcd@google.com>",
  "license": "Apache-2.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/googlemaps/transport-tracker.git"
  },
  "dependencies": {
    "ejs": "2.5.5"
  }
}
```

**Comment by kbihani** [comment]
Facing the same issue. Any leads on how to solve this?

**Comment by leonharbour** [comment]
I was able to display some content by accessing the admin folder via a web server. 
But I don't believe it was build to be used in that way.

It feels like an unfinished showcase project.

**Comment by domesticmouse** [comment]
@stephenmcd

**Comment by stephenmcd** [comment]
> But I don't believe it was built to be used in that way.

That's the correct way to access it - the JS is client-side and package.json exists so that the dependencies can be installed.
