### ISSUE TITLE
Integrating Real Bus Data

### ISSUE THREAD

**Issue by quarky912** [googlemaps/transport-tracker#36]
Please help me wit integrating a real bus data and making this project to display real bus location and time to each station on the map. @domesticmouse @stephenmcd

**Comment by domesticmouse** [comment]
The majority of the work required to integrate real bus data involves getting some form of GPS tracker installed on the buses that you are tracking. This is a non-trivial exercise, and well and truly outside the scope of this project.

**Comment by quarky912** [comment]
What about that android application provided in this tutorial for real time location tracking?  I think instead of a GPS tracker that app can be used. @domesticmouse

**Comment by domesticmouse** [comment]
That app is what we used to turn Android phones into GPS tracking units. We used Firebase Realtime Database to communicate the location of the buses in our fleet over 3G networks. Getting these phones installed on buses, working with the drivers, making sure the phones are powered, and so forth, is the basis of the challenge of setting up this operation.

**Comment by quarky912** [comment]
Exactly! This is what I'm saying, the app will be installed on the phones
of bus drivers and will be used as tracking devices.
I want to know what changes we need to do in our code which we are using
for simulations?
The app gives us "raw locations" in the Firebase database. how to use those
raw locations?
Can you please help me in developing a system for bus tracking? in which
users also have their own app to track the bus on a particular route they
wish to.

**Comment by domesticmouse** [comment]
The connection is in where in the firebase realtime database the front end pulls bus locations. You need to turn off the fake bus location provider and use the real locations. I believe we detail this out in the codelabs:

 - https://codelabs.developers.google.com/codelabs/transport-tracker-backend/index.html
 - https://codelabs.developers.google.com/codelabs/transport-tracker-map/index.html
 - https://codelabs.developers.google.com/codelabs/realtime-asset-tracking/index.html

**Comment by PaulOOlabisi** [comment]
Hello @domesticmouse , I am a newbie and I'm following the tutorial as well, and I would like to use the real bus location data. I have the android app set up following [this ](https://developers.google.com/maps/solutions/transport-tracker/start#step_6_set_up_the_android_app), and I have changed this to `"simulation": false`. The part where I'm stuck is here; `if (trackerConfig.simulation) {
  const {BusSimulator} = require('./bus_simulator.js');
  const generatedPaths = require('./paths.json');
  new BusSimulator(timeRef, gtfs, busLocationsRef, generatedPaths);
} else {
  // Exercise for the reader: integrate real bus location data
}`

**Comment by PaulOOlabisi** [comment]
Hello @domesticmouse , I am following the tutorial as well, and I would like to use the real bus location data. I have the android app set up following [this ](https://developers.google.com/maps/solutions/transport-tracker/start#step_6_set_up_the_android_app), and I have changed this to `"simulation": false`. The part where I'm stuck is here;
`if (trackerConfig.simulation) {`
  `const {BusSimulator} = require('./bus_simulator.js');`
  `const generatedPaths = require('./paths.json');`
  `new BusSimulator(timeRef, gtfs, busLocationsRef, generatedPaths);`
`} else {`
  `// Exercise for the reader: integrate real bus location data`
`}`

**Comment by domesticmouse** [comment]
Have you gone through the [realtime asset tracking codelab](https://codelabs.developers.google.com/codelabs/realtime-asset-tracking/index.html)? It contains the code you need to insert in that `else` clause.

**Comment by ankurparashar** [comment]
@domesticmouse I have read the codelabs, but realtime asset tracking codelab gives solution for Android App real time data handling. How to achieve the same in Web project setup in other codelabs. In short, what to write in else block for showing real device locations on map.
@PaulOOlabisi @quarkygit  did u find the solution?
