### ISSUE TITLE
index.html showing empty page 

### ISSUE THREAD

**Issue by SamiKhalid** [googlemaps/transport-tracker#37]
Dear Brett ... please check this screenshot : 
![sample](https://user-images.githubusercontent.com/36380631/36101862-96b79980-101b-11e8-9ea7-b24d1355d67f.png)
 
index.html showing empty page after running the npm !?

**Comment by domesticmouse** [comment]
Please open your javascript console. I'm guessing you will see messages about an invalid or missing API Key for Google Maps.

**Comment by SamiKhalid** [comment]
yes dear ... it's working now showing me all the buses and markers ... I guess now I have to modify index.js to show the location of the android device which successfully showing up in firebase real-time database...
thank you so much
