### ISSUE TITLE
How to integrate admin section.

### ISSUE THREAD

**Issue by rajqaiser** [googlemaps/transport-tracker#38]
I am implemented the back-end and Map section from this [Link](https://codelabs.developers.google.com/).
Back-end and Map section worked fine but i am confuse about Admin section. How we integrate the Admin section with rest of the section. ? Where i need to deploy admin section. ? How we can see the live tracking of vehicle.? Currently on map all markers are initialize first time and then  don't change with respect to change the location. 
Thanks

**Comment by domesticmouse** [comment]
The admin section is a purely reporting interface to enable maintenance of the phone trackers. It was used during I/O to keep a track of battery levels on the phones so we were aware when they became unplugged and that sort of thing.

As to tracking live buses, you need to point the front end at the live data that your phone trackers are reporting. If you have worked through the codelabs the changes required should be self evident.
