### ISSUE TITLE
not showing live tracking of bus on map

### ISSUE THREAD

**Issue by saifi346** [googlemaps/transport-tracker#39]
Hey @quarky912 are you able to show locations of buses on map I'm also facing the same problem. I'm getting those locations in raw data but it's not showing in web app please tell me if you got this I've been working on it from weeks but I'm not getting how to show those locations on map

**Comment by domesticmouse** [comment]
You need to change the front end code to read from where ever in the firebase real time database store that you are writing the real time locations to. In the real system I cleaned up locations of the buses by a couple of minutes of bus location history past the [Google Maps Roads API](https://developers.google.com/maps/documentation/roads/intro) to tidy up location data to deal with the inherent noise in GPS location tracking.
