### ISSUE TITLE
Why not GTFS data in Firebase?

### ISSUE THREAD

**Issue by HariniPalanisamy** [googlemaps/transport-tracker#47]
GTFS data is stored in **SQLite**. I'm just wondering why not store them in **Firebase**, so everything is in single database. Correct me if my question is silly. Thanks in advance.

**Comment by domesticmouse** [comment]
First time around I stored everything in firebase realtime database. The thing is, firebase realtime database is a communication medium, not a query able database. Look at the queries I fire at sqlite and think about how you'd run those against firebase....

**Comment by HariniPalanisamy** [comment]
Agreed!
