### ISSUE TITLE
npm run main fails.

### ISSUE THREAD

**Issue by gbasiemseverest** [googlemaps/transport-tracker#48]
Thank you for sharing the amazing piece of your work,

I followed your well explained steps to reach here, but i couldn't npm run main to the backend.
I am continuously receiving the error,

TypeError: Cannot read property 'legs' of undefined

![image](https://user-images.githubusercontent.com/31979430/43442467-be3f8996-94bd-11e8-932d-05a099ba511c.png)

As suggested by few fellow programmers, i upgraded the npm version to 6.2 but still couldn't get any solution then i even downgraded to the version 4.6.1 still i am not getting anywhere.
Any help will be highly appreciated. Thank You

**Comment by monikagupta78** [comment]
I am also getting same error, were you able to fix this?

**Comment by domesticmouse** [comment]
`legs` is supposed to be an attribute of the returned data, the fact that it is absent is indicative of there being no routes available. I should really add some error handling.

**Comment by monikagupta78** [comment]
@domesticmouse  -  does it mean we are good with backend setup? How to confirm the same?

**Comment by domesticmouse** [comment]
Have you gone through the transport tracker codelabs?

**Comment by hynra** [comment]
```javascript
const ptt = this.directionsResponseForTrip(returnValue.next_trip.trip);
````

I faced same issue. If you print `ptt`, it's return message `This API project is not authorized to use this API`. I've resolved this issue by changing Maps API key in `tracker_configuration.js` from API Key to Server Key. I realized that The Getting Started (https://developers.google.com/maps/solutions/transport-tracker/start) is guide me to copy the API Key instead of Server Key.

**Comment by humbertn** [comment]
Hi @hynra where can I get the "Server Key" that you mention, thanks for you answer.

**Comment by Maphila** [comment]
@hynra The Server Key (from firebase) is giving out errors?

**Comment by sayuti-daniel** [comment]
The project uses [Directions API](https://console.developers.google.com/apis/library/directions-backend.googleapis.com). Enable the API, then it will work.
https://github.com/googlemaps/transport-tracker/blob/0146b3ec8246b808536a3cfbbf721d1a51444a5f/backend/time_table.js#L205-L206


Server Key is just a credential name generated by Google Service. For testing purposes, just ensure that the used API key doesn't have restrictions.
