### ISSUE TITLE
How to bring up admin module

### ISSUE THREAD

**Issue by monikagupta78** [googlemaps/transport-tracker#50]
I did npm install for admin module also added API key and call. 

I don't see any index.js file. I tried to run npm main.js , got below error

ReferenceError: firebase is not defined.

If i open the index.html page, nothing shows up. in debug, I can see this error:
Uncaught TypeError: Cannot convert undefined or null to object firebase.js:320 Uncaught TypeError: Cannot convert undefined or null 
    at Function.keys (<anonymous>)
    at main.js:36
    at firebase.js:424
    at ub (firebase.js:320)
    at Rb (firebase.js:308)
    at Sb (firebase.js:307)
    at Object.G (firebase.js:493)
    at firebase.js:465
    at Pg.g.wd (firebase.js:470)
    at Ce.wd (firebase.js:372)

Any inputs pls?

**Comment by hynra** [comment]
Just open `index.html`  with browser. No need `npm`

**Comment by rpputra** [comment]
I have the same issue
![image](https://user-images.githubusercontent.com/36644595/64682441-a983e400-d4ab-11e9-841f-253af43fc511.png)
