### ISSUE TITLE
Unable to render map

### ISSUE THREAD

**Issue by rfigueror1** [googlemaps/transport-tracker#53]
Hi everybody, 

I have successfully started both the backend and the map servers with no error shown in the terminal. Nevertheless I am trying to see the results on my localhost:8080 and only the rendering of static files from the title are shown. I have not initialized any other devices.

![screenshot from 2018-09-24 14-20-08](https://user-images.githubusercontent.com/31106549/45973770-01a8a880-c005-11e8-8381-3d9602cfe3b5.png)

**Comment by domesticmouse** [comment]
I'd be intrigued to know if there are any console log entries.

**Comment by MattheusOliveira** [comment]
Hi, the same situation is happening to me. Follows the console log.

![error](https://user-images.githubusercontent.com/29807852/46251716-5b5c0900-c431-11e8-8045-1673806dda64.png)

**Comment by micohalvarez** [comment]
Hello I same problem with me. The map is not rendering somehow. 

![image](https://user-images.githubusercontent.com/14908302/46269960-2ce84600-c577-11e8-9327-9c5df3089e85.png)

**Comment by MattheusOliveira** [comment]
Has anyone managed to solve the map rendering problem? Is there any reason what might cause this at the time of setup?

**Comment by domesticmouse** [comment]
@MattheusOliveira did you succeed in changing the firebase app name? Without Firebase correctly configured not much of anything is going to happen.

@micohalvarez You need to click on the Console tab in the lower pane to see console log error messages. Here's some documentation on how to use devtools: https://developers.google.com/web/tools/chrome-devtools/

**Comment by ambouh** [comment]
I'm also having the same issue, I have enable my APIs, I think the map is not rendering on time and is halted when the page has completed loading?
![image](https://user-images.githubusercontent.com/17465687/59342736-534eab80-8cd8-11e9-8275-45614e9c2194.png)
