### ISSUE TITLE
Map is not coming up

### ISSUE THREAD

**Issue by aaamitsingh** [googlemaps/transport-tracker#59]
Hi,
Today I'm trying this project by following the mentioned steps given is the below link:
https://developers.google.com/maps/solutions/transport-tracker/start?refresh=1
I have compleated the "Step 4. Set up the backend" and I can see the data on the db:
![image](https://user-images.githubusercontent.com/25000347/53712891-c8efe380-3e6e-11e9-8646-aa1ea128ca16.png)
But I'm facing an issue in the "Step 5. Create the map" here the program is executed without any error 
![image](https://user-images.githubusercontent.com/25000347/53713040-59c6bf00-3e6f-11e9-9e4d-e1d1c1db8352.png)
but I can't see the map on the ip "http://35.197.142.12:8080/"
![image](https://user-images.githubusercontent.com/25000347/53713074-79f67e00-3e6f-11e9-8756-1f0256cee3b3.png)

**Comment by domesticmouse** [comment]
This isn't the right issue tracker for the Google Maps developers documentation. Please raise an issue on this [issue tracker](https://developers.google.com/maps/support/?refresh=1#issue_tracker).
