### ISSUE TITLE
que

### ISSUE THREAD

**Issue by Hager777** [googlemaps/transport-tracker#62]
please help me to solve this error

Error: Cannot find module './gtfs.js'

**Comment by amuramoto** [comment]
What file is throwing the error? Do you have the entire repo downloaded?

**Comment by mikebernal** [comment]
wow someone replied. Thanks though Already solved it.
Best Regards,
Mike Bernal

M: 0415 030 932
E: mikebernal.me@gmail.com


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
