### ISSUE TITLE
Backend Error: Bus error (core dumped)  when "npm run main"

### ISSUE THREAD

**Issue by Faithful1** [googlemaps/transport-tracker#63]
I have supplied all the necessary credentials as stated in the documentation and have run npm install for the backend but then i get the error as below

`
Bus error (core dumped)

npm ERR! Linux 4.15.0-50-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "main"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! transport-tracker-server@1.0.0 main: `node main.js`
npm ERR! Exit status 135
npm ERR! 
npm ERR! Failed at the transport-tracker-server@1.0.0 main script 'node main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the transport-tracker-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs transport-tracker-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls transport-tracker-server
npm ERR! There is likely additional logging output above.`

Please how do i get past this.
i am using ubuntu 18.04

**Comment by Mo9a7i** [comment]
this repo is dead brother, it has a lot of missing information and outdated dependencies.
I don't know why it's still held under googlemaps account and shows up on google's results page for gps tracking keywords.

**Comment by Faithful1** [comment]
well then that is sad
