### ISSUE TITLE
Failed to start: NPM RUN MAIN

### ISSUE THREAD

**Issue by snvz2** [googlemaps/transport-tracker#7]
Hello Author,

Thank you for sharing your transport-tracker code.

I am having an issue with starting the Server. Attached a log for reference.

Node.js and NPM installed OK, android code compiled fine, Google Maps API keys included in the code and the project is connected to the database (tested the connection fine).
However the server fails to start:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'main' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose run-script [ 'premain', 'main', 'postmain' ]
5 info lifecycle display-server@1.0.0~premain: display-server@1.0.0
6 silly lifecycle display-server@1.0.0~premain: no script for premain, continuing
7 info lifecycle display-server@1.0.0~main: display-server@1.0.0
8 verbose lifecycle display-server@1.0.0~main: unsafe-perm in lifecycle true
9 verbose lifecycle display-server@1.0.0~main: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\CSTransportTracker\display-server\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;;C:\Program Files\Autodesk Git Bundle\cmd;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Common Files\Autodesk Shared\;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\Users\t_zarun\AppData\Roaming\npm
10 verbose lifecycle display-server@1.0.0~main: CWD: C:\CSTransportTracker\display-server
11 silly lifecycle display-server@1.0.0~main: Args: [ '/d /s /c', 'nodemon main.js' ]
12 silly lifecycle display-server@1.0.0~main: Returned: code: 1  signal: null
13 info lifecycle display-server@1.0.0~main: Failed to exec main script
14 verbose stack Error: display-server@1.0.0 main: `nodemon main.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid display-server@1.0.0
16 verbose cwd C:\CSTransportTracker\display-server
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "main"
19 error node v6.10.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error display-server@1.0.0 main: `nodemon main.js`
22 error Exit status 1
23 error Failed at the display-server@1.0.0 main script 'nodemon main.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the display-server package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     nodemon main.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs display-server
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls display-server
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by domesticmouse** [comment]
I'm not sure what the cause of the failure is in this stack trace. I suspect that nodemon is either not installed, or is unhappy on Windows. I develop on macOS, and deploy on Linux. I'm unsure of the stability status of Node and it's various NPM packages on Windows. I'd suggest trying again on Windows Subsystem for Linux, if you are running the Creators update of Win10...

**Comment by dipakparmar** [comment]
Hello Author,

Also I'm getting this error 
 C:\wamp\www\backend> npm run main

transport-tracker-server@1.0.0 main C:\wamp\www\backend
node main.js

\wamp\www\backend\node_modules\firebase-admin\lib\auth\credential.js:108
          throw new error_1.FirebaseAppError(error_1.AppErrorCodes.INVALID_CREDENTIAL, errorMess
          ^

ror: Certificate object must contain a string "private_key" property.
  at FirebaseAppError.FirebaseError [as constructor] (C:\wamp\www\backend\node_modules\firebase-
:25:28)
  at new FirebaseAppError (C:\wamp\www\backend\node_modules\firebase-admin\lib\utils\error.js:70
  at new Certificate (C:\wamp\www\backend\node_modules\firebase-admin\lib\auth\credential.js:108
  at new CertCredential (C:\wamp\www\backend\node_modules\firebase-admin\lib\auth\credential.js:
  at Object.cert (C:\wamp\www\backend\node_modules\firebase-admin\lib\firebase-namespace.js:175:
  at Object.<anonymous> (C:\wamp\www\backend\main.js:28:32)
  at Module._compile (module.js:569:30)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (module.js:503:32)
  at tryModuleLoad (module.js:466:12)
  at Function.Module._load (module.js:458:3)
  at Function.Module.runMain (module.js:605:10)
  at startup (bootstrap_node.js:158:16)
  at bootstrap_node.js:575:3
m ERR! code ELIFECYCLE
m ERR! errno 1
m ERR! transport-tracker-server@1.0.0 main: `node main.js`
m ERR! Exit status 1
m ERR!
m ERR! Failed at the transport-tracker-server@1.0.0 main script.
m ERR! This is probably not a problem with npm. There is likely additional logging output above.

m ERR! A complete log of this run can be found in:
m ERR!     C:\Users\dipak\AppData\Roaming\npm-cache\_logs\2017-07-27T04_30_13_884Z-debug.log

here is the the log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'main' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose run-script [ 'premain', 'main', 'postmain' ]
5 info lifecycle transport-tracker-server@1.0.0~premain: transport-tracker-server@1.0.0
6 info lifecycle transport-tracker-server@1.0.0~main: transport-tracker-server@1.0.0
7 verbose lifecycle transport-tracker-server@1.0.0~main: unsafe-perm in lifecycle true
8 verbose lifecycle transport-tracker-server@1.0.0~main: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\wamp\www\backend\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\oraclexe\app\oracle\product\10.2.0\server\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Broadcom\Broadcom 802.11\Driver;C:\Program Files\Git\cmd;C:\wamp\bin\php\php5.6.25;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs\;C:\Users\dipak\AppData\Roaming\Composer\vendor\bin;C:\Users\dipak\AppData\Local\Microsoft\WindowsApps;C:\Users\dipak\AppData\Roaming\npm
9 verbose lifecycle transport-tracker-server@1.0.0~main: CWD: C:\wamp\www\backend
10 silly lifecycle transport-tracker-server@1.0.0~main: Args: [ '/d /s /c', 'node main.js' ]
11 silly lifecycle transport-tracker-server@1.0.0~main: Returned: code: 1  signal: null
12 info lifecycle transport-tracker-server@1.0.0~main: Failed to exec main script
13 verbose stack Error: transport-tracker-server@1.0.0 main: `node main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:921:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid transport-tracker-server@1.0.0
15 verbose cwd C:\wamp\www\backend
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "main"
18 verbose node v8.2.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error transport-tracker-server@1.0.0 main: `node main.js`
22 error Exit status 1
23 error Failed at the transport-tracker-server@1.0.0 main script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by domesticmouse** [comment]
@dipakparmar given you have invalid credential as the error, my suspicion is that you haven't installed all the required API keys. Please read through https://codelabs.developers.google.com/codelabs/transport-tracker-backend and https://codelabs.developers.google.com/codelabs/transport-tracker-map to get insight on how to do this. Thanks!

**Comment by chipcerio** [comment]
I'm at Codelabs step 5 where you do a simulation with a heartbeat.  Got an error when running `npm run main`

here's the log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/nvm/versions/node/v6.11.1/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'main' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 verbose run-script [ 'premain', 'main', 'postmain' ]
5 info lifecycle transport-tracker-server@1.0.0~premain: transport-tracker-server@1.0.0
6 silly lifecycle transport-tracker-server@1.0.0~premain: no script for premain, continuing
7 info lifecycle transport-tracker-server@1.0.0~main: transport-tracker-server@1.0.0
8 verbose lifecycle transport-tracker-server@1.0.0~main: unsafe-perm in lifecycle true
9 verbose lifecycle transport-tracker-server@1.0.0~main: PATH: /usr/local/nvm/versions/node/v6.11.1/lib/node_modules/npm/bin/node-gyp-bin:/home/alistair_cerio/transport-tracker-server/node_modules/.bin:/usr/local/nvm/versions/node/v6.11.1/bin:/google/google-cloud-sdk/bin:/home/alistair_cerio/gopath/bin:/google/gopath/bin:/google/google-cloud-sdk/bin:/usr/local/go/bin:/gradle-2.12/bin:/apache-maven-3.3.9/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/nvm/versions/node/v6.11.1/bin:/google/go_appengine:/google/google_appengine
10 verbose lifecycle transport-tracker-server@1.0.0~main: CWD: /home/alistair_cerio/transport-tracker-server
11 silly lifecycle transport-tracker-server@1.0.0~main: Args: [ '-c', 'node main.js' ]
12 silly lifecycle transport-tracker-server@1.0.0~main: Returned: code: 1  signal: null
13 info lifecycle transport-tracker-server@1.0.0~main: Failed to exec main script
14 verbose stack Error: transport-tracker-server@1.0.0 main: `node main.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/nvm/versions/node/v6.11.1/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/nvm/versions/node/v6.11.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid transport-tracker-server@1.0.0
16 verbose cwd /home/alistair_cerio/transport-tracker-server
17 error Linux 3.16.0-4-amd64
18 error argv "/usr/local/nvm/versions/node/v6.11.1/bin/node" "/usr/bin/npm" "run" "main"
19 error node v6.11.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error transport-tracker-server@1.0.0 main: `node main.js`
22 error Exit status 1
23 error Failed at the transport-tracker-server@1.0.0 main script 'node main.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the transport-tracker-server package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node main.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs transport-tracker-server
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls transport-tracker-server
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by domesticmouse** [comment]
@chipcerio I honestly have no idea what went wrong here, there is nothing that stands out in the log that points to a cause. Have you tried running the final version of the code from github to see if your system is sane?

**Comment by atharvaunde59** [comment]
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/nvm/versions/node/v6.11.1/bin/node" "/usr/bin/npm" "run" "main"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
atharv_unde59@pccoe2018-f9f05:~$ pwd
/home/atharv_unde59
atharv_unde59@pccoe2018-f9f05:~$ npm run main
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/nvm/versions/node/v6.11.1/bin/node" "/usr/bin/npm" "run" "main"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! path /home/atharv_unde59/package.json
npm ERR! code ENOENT
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/atharv_unde59/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/atharv_unde59/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/atharv_unde59/npm-debug.log




am getting this issue although package.json is there at same path

**Comment by domesticmouse** [comment]
@atharvaunde59 I suspect you need to change directory into the checkout...

**Comment by ghzoan** [comment]
1 week trying installing google map, and the map not showing at all

finally im using now google cloud shell its must be without error 

but in backend installing process go this 
npm ERR! transport-tracker-server@1.0.0 main: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the transport-tracker-server@1.0.0 main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


and in map process the process stuck 

i think there something wrong with this I tried all the steps many times and many alternative link, just this one not working with me the others showing the map

please any help! 

gps.jernascenter.com    in this link you will see the third test how its not showing the map and admin panel also 
![screenshot 43](https://user-images.githubusercontent.com/7097936/35542742-bf2645aa-0572-11e8-87b4-7d687a14dc84.png)

**Comment by naeemjawaid** [comment]
Updating npm on server worked for me.
